# Generated by Django 5.0.6 on 2024-06-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_alter_companies_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='company_value',
            field=models.FloatField(default=100.112),
            preserve_default=False,
        ),
    ]
