# Generated by Django 5.0.6 on 2024-06-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_rename_company_value_companies_company_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='date',
            field=models.DateField(),
        ),
    ]
