# Generated by Django 5.0.6 on 2024-06-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_alter_companies_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
