# Generated by Django 5.0.6 on 2024-06-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_alter_companies_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='company_close',
            field=models.FloatField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='company_high',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='company_low',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='company_open',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
    ]
